# -*- coding: utf-8 -*-
"""AI-Based_Resume_Matcher.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O9MMrExXt6GXYhph2rR5fWM1qfpPFGFG
"""

import gradio as gr
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import PyPDF2


data = {
    "Job Role": [
        "Data Analyst",
        "Data Scientist",
        "Web Developer",
        "Software Engineer",
        "Accountant",
        "MIS Executive"
    ],
    "Skills": [
        "Excel SQL Power BI Python Data Analysis",
        "Python Machine Learning AI Statistics Deep Learning",
        "HTML CSS JavaScript React Node",
        "Java C++ DSA Problem Solving OOP",
        "Tally GST Accounting Excel Finance",
        "Advanced Excel MIS Reporting VLOOKUP Pivot Table"
    ]
}

df = pd.DataFrame(data)

def extract_text_from_pdf(file):
    text = ""
    pdf_reader = PyPDF2.PdfReader(file)
    for page in pdf_reader.pages:
        text += page.extract_text() or ""
    return text


def match_resume(file):
    if file is None:
        return "Please upload a resume."

    try:
        if file.name.endswith(".pdf"):
            resume_text = extract_text_from_pdf(file)
        else:
            resume_text = file.read().decode("utf-8")
    except:
        return "Error reading file. Please upload a valid PDF or TXT."

    if len(resume_text.strip()) == 0:
        return "Resume seems empty."

    corpus = df["Skills"].tolist()
    corpus.append(resume_text)

    vectorizer = TfidfVectorizer(stop_words="english")
    vectors = vectorizer.fit_transform(corpus)

    similarity = cosine_similarity(vectors[-1], vectors[:-1])
    best_index = similarity.argmax()

    job = df.iloc[best_index]["Job Role"]
    score = similarity[0][best_index]

    top_indices = similarity[0].argsort()[-3:][::-1]

    results = "Top Job Matches:\n\n"
    for i in top_indices:
        results += f"{df.iloc[i]['Job Role']} → {round(similarity[0][i]*100,2)}%\n"

    return results


interface = gr.Interface(
    fn=match_resume,
    inputs=gr.File(label="Upload your Resume (PDF or TXT)"),
    outputs="text",
    title="AI Resume Job Matcher",
    description="Upload your resume and get the best matching job roles"
)

interface.launch()